[package]
name = "upgen"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
typestate = "0.8.0"
bytes = "1.1.0"
tokio = { version = "1.17.0", features = ["macros", "rt", "rt-multi-thread", "io-util", "net"] }
async-trait = "0.1.0"
